<?php
  echo $this->inlineScript(\Laminas\View\Helper\HeadScript::FILE, 'openurl.js', 'SET');
  $openUrl = $this->openUrl($this->driver, 'record');

  $openUrlHelper = $this->openUrl($this->driver, 'record');
  $services = $openUrlHelper->getActiveServices();
  $serviceList = implode(',', $services);
?>
<span class="openUrlControls openUrlEmbed">
  <a href="" class="fulltext" data-search-class-id="<?=$this->escapeHtmlAttr($this->searchClassId) ?>">
    <span title="<?=$this->escapeHtmlAttr($this->driver->getOpenUrl())?>" class="openUrl"></span>
    <span title="<?=$this->escapeHtmlAttr($this->recordId) ?>" class="recordId"></span>
    <span title="<?=$this->escapeHtmlAttr($serviceList) ?>" class="resolverService"></span>
  </a>
</span>
<div class="resolver hidden"><?=$this->transEsc('Loading')?>...</div>
